##########################################
##     PostPone configuration file      ##
## ------------------------------------ ##
## Developed by SkyIrc development team ##
## Copyright (c) SkyIrc                 ##
## Licensed under GNU GPL 3             ##
##########################################

# This file stores the configuration of your
# PostPone instance.
# Do NEVER remove the .htaccess from this directory,
# else your configuration including all passwords
# is readable by everyone!

####################
# MySQL Connection #
####################

mysql:
  
  # MySQL server
  server: localhost
  
  # Username to connect to the MySQL server
  user: postpone
  
  # Password for the user specified above
  password: password
  
  # Database name
  database: postpone
  
  # Table prefix
  prefix: pp_
  
  

####################
# Meta information #
####################

meta:
  
  # Title of the website
  title: PostPone
  
  # Author
  author: SkyIrc development team
  
  # Copyright
  copyright: Copyright (c) SkyIrc
  
  # Keywords (comma seperated)
  keywords: PostPone, CMS, SkyIrc
  
  # Description
  description: PostPone CMS


####################
# Cookies/Sessions #
####################

session:

  # Cookie prefix
  cookie_prefix: pp_

  # Cookie domain
  cookie_domain: ''

  # Cookie path
  cookie_path: ''

  # Standard session duration (seconds)
  # Standard: 1800 (30 minutes)
  sess_duration: 1800

  # Long session duration (seconds)
  # Standard: 15768000 (half a year)
  sess_long_duration: 15768000

#################
# User settings #
#################

user:

  # Default user group
  def_group: 1

  # Guest group
  guest_group: 0
  

#################
# Miscellaneous #
#################

# Template (name of the directory in /templates)
template: woobie

# Standard locale
locale: en_UK

# Standard page (short name)
std_page: home